language: node_js

sudo: required
services:
  - docker

node_js:
  - "lts/*"

stage:
  - lint
  - test

jobs:
  include:
    - stage: lint
      script:
        - cd ./backend
        - npm install
        - npm run lint
    - stage: test
      script:
        - cd ./backend
        - npm install
        - sudo docker run -p 27017:27017 -d mongo
        - npm run test